### ISSUE TITLE
USER STORY: SOUNDS

### ISSUE THREAD

**Issue by DarrachBarneveld** [broken-helix/happiness#104]
As a **user** I can **hear music and sounds** so that ** feel happy and notice every interaction**.

### Acceptance Criteria: 
The website has a theme music
Buttons have fun sound effects

### Tasks:

- [ ] Add music to the site
- [ ] Add a play button
- [ ] Add sound effects to buttons

---
